### ISSUE TITLE
feat: Columns with named sorting options

### ISSUE THREAD

**Issue by Zetanova** [Maxl94/ngx-multi-sort-table#201]
It is often required to fit a table in a viewport by compacting it.
A column holds then a composite value. 

An example would instead to have "Contact Name", "Contact Email", "Contact Mobile" the columns are joined into one "Contact".

The issue with this approach is that the multi sort is then limited to a default comparison of the column and 
the user choose to sort by a specific value. 

My idea to solve this is to add an option on the column configuration for named sorting options.

In the above example the "Contact" column would have "Email" and "Mobile" as a named sorting.
It could be displayed in the sorting-toolbar like "Contact (Mobile)"

**Comment by Maxl94** [comment]
I see the problem. And your proposed solution looks from my obvious. 

@Catscratch do you see any problems?

**Comment by Catscratch** [comment]
I hope I understood it correctly.

You're asking for a feature to specify different sorting algorithms for ONE column?

E.g. Sort column "Contacts" by firstname, lastname or company?

If so, I'm not sure this is a good idea from usability point of view. We're trying to align the UX with the material design guide. There a column should be sorted by one criterion and that should usually "what you see". E.g. If you have a combined column like "Firstname, Lastname (Company)" you should sort by firstname because that makes sense for the user. He can directly understand how the sorting works.

If you sort by e.g. company the rows seem to be mixed for the user. Then the better approach would be to have two separate columns instead of one joint one.

**Comment by Zetanova** [comment]
The single column approach per value does not work in practice. It is even true for ms-excel.
Most of bigger table require some multi value column. 

My current approach is to create for each value a hidden column for the user to sort by activating the column and sorting by it.

```ts
type DataTableColumn = {
  id: string;
  name: string;
  isActive?: boolean;
  sortBy?: string|boolean;
}

//defne the columns
const columns:DataTableColumn = [
    { id: 'contact', name: 'Contact', sortBy: 'contactName' },
    { id: 'contactName', name: 'Contact', isActive: false, sortBy: 'contactName' },
    { id: 'contactCompany', name: 'Contact Company', isActive: false, sortBy: 'contactCompany' },
   //...
]

//create the table
const table = new TableData<any>(
      columns,
      {
        localStorageKey: `${name}-table`
      }
    )

//read the sorting columns
var sort = [];

for (var i = 0; i < table.sortParams.length; i++) {
     let sortBy = table.sortParams[i]
     let dir = table.sortDirs[i]

      const column = columns.find(n => n.id === sortBy)
      if(!column)
        continue //ignore
      if(typeof column.sortBy === 'string')
        sortBy = column.sortBy

      sort.push(`${sortBy} ${dir}`)
}

```

**Comment by Catscratch** [comment]
I understand your problem, but I still think that this would violate usability of the [Material Design Principles](https://m2.material.io/components/data-tables#anatomy).
